server.port=0

# id приложения
spring.application.name=EurekaClient2

# url, куда будет происходить регистрация микросервисов
eureka.client.service-url.defaultZone="http://localhost:8081/eureka"

# более коротное отображение логов
logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n